[manager]
ratio = [1, 2, 3]
show_hidden = false

[plugin]
previewers = [
    { name = "*/", run = "folder", sync = true },
    { name = "*.csv", run = "bat" },
    { name = "*.md", run = "bat" },
    { mime = "text/*", run = "bat" },
    { mime = "*/xml", run = "bat" },
    { mime = "*/cs", run = "bat" },
    { mime = "*/javascript", run = "bat" },
    { mime = "*/x-wine-extension-ini", run = "bat" }
]
